export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Investors } from './Investors'
export { default as FAQ } from './Faq'
export { default as Contact } from './Contact'
